compress_assets:       on
gzip_assets:           off
javascript_compressor: uglifier
package_path:          assets/js

javascripts:
  libraries:
    - vendor/javascripts/**/*.js
  script:
    - app/assets/javascripts/*.js
