dev:
  name:
  user:
  password:
  host: localhost
  grant_to: localhost
  tbl_prefix: wp_

staging:
  name:
  user:
  password:
  host:
  grant_to: localhost
  tbl_prefix: wp_

production:
  name:
  user:
  password:
  host:
  grant_to: localhost
  tbl_prefix: wp_
