# Project information
name: starter-wp
repo: git://github.com/TomodomoCo/starter-wp.git

uploads:
  - public/assets

# Deploy alerts
alerts:
  slack:
    channel: 'activity'
    webhook: 'https://hooks.slack.com/services/X/X/X'

# Deployment stages
stage:
  dev:
    ip: 10.1.1.50
    ports:
      ssh: 22
    user: vagrant
    domain: dev.domain.com
  staging:
    ip: 0.0.0.0
    ports:
      ssh: 22
    user: deploy
    branch: staging
    domain: staging.domain.com
  production:
    ip: 0.0.0.0
    ports:
      ssh: 22
    user: deploy
    branch: production
    domain: domain.com
