dev:
  name: dev
  user: root
  password: root
  host: localhost
  tbl_prefix: wp_
staging:
  name:
  user:
  password:
  host: localhost
  tbl_prefix: wp_
production:
  name:
  user:
  password:
  host: localhost
  tbl_prefix: wp_